@extends('layouts.frontend')

@section('content')
    <div class="entry-content">
        <h5><strong>RISKS ASSOCIATED WITH FOREX TRADING</strong></h5>
        <p>Trading foreign currencies can be a challenging and potentially profitable opportunity for investors. However, before deciding to participate in the Forex market, you should carefully consider your investment objectives, level of experience, and risk appetite. Most importantly, do not invest money you cannot afford to lose.</p>
        <p>There is considerable exposure to risk in any foreign exchange transaction. Any transaction involving currencies involves risks including, but not limited to, the potential for changing political and/or economic conditions that may substantially affect the price or liquidity of a currency. Investments in foreign exchange speculation may also be susceptible to sharp rises and falls as the relevant market values fluctuate. The leveraged nature of Forex trading means that any market movement will have an equally proportional effect on your deposited funds. This may work against you as well as for you. Not only may investors get back less than they invested, but in the case of higher risk strategies, investors may lose the entirety of their investment. It is for this reason that when speculating in such markets it is advisable to use only risk capital.</p>
        <hr>
        <h5><strong>RISK DISCLAIMER FOR FOREX TRADING</strong></h5>
        <p>Trading foreign exchange on margin carries a high level of risk, and may not be suitable for all investors. Past performance is not indicative of future results. The high degree of leverage can work against you as well as for you. Before deciding to invest in foreign exchange you should carefully consider your investment objectives, level of experience, and risk appetite. The possibility exists that you could sustain a loss of some or all of your initial investment and therefore you should not invest money that you cannot afford to lose. You should be aware of all the risks associated with foreign exchange trading, and seek advice from an independent financial advisor if you have any doubts.</p>
        <hr>
        <h5><strong>BENEFITS AND RISK OF LEVERAGE<br>
            </strong></h5>
        <p>Leverage allows traders the ability to enter into a position worth many times the account value with a relatively small amount of money. This leverage can work with you as well as against you. Even though the Forex market offers traders the ability to use a high degree of leverage, trading with high leverage may increase the losses suffered. Please use caution when using leverage in trading or investing.</p>
        <hr>
        <h5><strong>HYPOTHETICAL&nbsp;RESULTS DISCLAIMER</strong></h5>
        <p><strong>THE RESULTS FOUND ON THIS WEBSITE ARE BASED ON SIMULATED OR HYPOTHETICAL PERFORMANCE RESULTS THAT HAVE CERTAIN INHERENT LIMITATIONS. UNLIKE THE RESULTS SHOWN IN AN ACTUAL PERFORMANCE RECORD, THESE RESULTS DO NOT REPRESENT ACTUAL TRADING. ALSO, BECAUSE THESE TRADES HAVE NOT ACTUALLY BEEN EXECUTED, THESE RESULTS MAY HAVE UNDER-OR OVER-COMPENSATED FOR THE IMPACT, IF ANY, OF CERTAIN MARKET FACTORS, SUCH AS LACK OF LIQUIDITY. SIMULATED OR HYPOTHETICAL TRADING PROGRAMS IN GENERAL ARE ALSO SUBJECT TO THE FACT THAT THEY ARE DESIGNED WITH THE BENEFIT OF HINDSIGHT. NO REPRESENTATION IS BEING MADE THAT ANY ACCOUNT WILL OR IS LIKELY TO ACHIEVE PROFITS OR LOSSES SIMILAR TO THESE BEING SHOWN.</strong></p>
        <p>The information that may be presented is based on simulated trading using systems and education developed exclusively by MTI. Simulated results do not represent actual trading. Please note that simulated trading results may or may not have been back-tested for accuracy and that spreads/commissions are not taken into account when preparing hypothetical results.</p>
        <p>No representation is being made that any account will or is likely to achieve profits or losses similar to those that may be shown. Past performance is not indicative of future results. Individual results vary and no representation is made that clients will or are likely to achieve profits or incur losses comparable to those that may be shown.</p>
        <hr>
        <h5><strong>RISKS ASSOCIATED WITH OPTIONS TRADING</strong></h5>
        <p>Options involve substantial risk and are not suitable for all investors. Options investors may lose the entire amount of their investment in a relatively short period of time. It is possible to owe more than you have invested in your brokerage account. Please be aware of your broker’s requirements for trading options. Before you decide to invest in the options market you should carefully consider your investment objectives, level of experience, and risk appetite. The possibility exists that you could sustain a substantial loss which could total more than your initial investment in a short period of time. Therefore you should not invest money that you cannot afford to lose. If you have any questions or concerns regarding the risks associated with option trading, you should confer with a trusted and reliable independent financial advisor. None of the information provided by FX NEWS TRADER 999 constitutes a solicitation to trade any investment or security of any kind.</p>
        <p>FX NEWS TRADER 999 and/or its personnel may or may not own positions and/or trade any securities that are the subject of the education and subsequent information we provide. FX NEWS TRADER 999 is not affiliated with nor do we have any relationship with any brokers that you may open an account with.</p>
        <p>Past performance is not indicative of future results. You acknowledge and agree that no promise or guarantee of success or profitability has been made between you and FX NEWS TRADER 999. Testimonials as presented may not be representative of all reasonably comparative clients.</p>
        <hr>
        <h5><strong>ELECTRONIC TRADING LISTS</strong></h5>
        <p>Before you engage in transactions using an electronic system, you should carefully review the rules and regulations of the exchanges offering the system and/or listing the instruments you intend to trade. Online trading has inherent risk due to system response and access times that may vary due to market conditions, system performance, and other factors. You should understand these and additional risks before trading.</p>
        <hr>
        <h5><strong>FX NEWS TRADER 999&nbsp;MARKET OPINIONS</strong></h5>
        <p>Any opinions, news, research, analyses, prices, or other information offered by FX NEWS TRADER 999 is provided as general market commentary, and does not constitute investment advice. FX NEWS TRADER 999&nbsp;will not accept liability for any loss or damage, including without limitation to, any loss of profit, which may arise directly or indirectly from use of or reliance on such information.</p>
        <hr>
        <h5><strong>RISKS ASSOCIATED WITH TRADING THE FOREX&nbsp;MARKET</strong></h5>
        <p>All investments involve risk, and the past performance of a security, industry, sector, market, financial product, trading strategy, or individual’s trading does not guarantee future results or returns. Investors are fully responsible for any investment decisions they make. Such decisions should be based solely on an evaluation of their financial circumstances, investment objectives, risk tolerance, and liquidity needs.</p>
        <p>Any opinions, news, research, analyses, prices, or other information offered by FX NEWS TRADER 999 is provided as general market commentary, and does not constitute investment advice. MTI will not accept liability for any loss or damage, including without limitation any loss of profit, which may arise directly or indirectly from use of or reliance on such information.</p>
    </div>
@endsection
